#!/usr/bin/env python3
"""Build-time assembler for scenario-specialized dobby skill sets.

Replaces the runtime dispatcher + backend architecture: instead of shipping
every backend and routing on `.dobby/config.json` at invocation, this tool
assembles a flat, scenario-specialized skill set per project from the source
tiers under `skills/` (`_lib`, `_common`, `ado`, `github`, `combined`) and a
single `skills/manifest.json`.

Modes:
  build [--out DIR]        Emit all three scenarios to DIR/<scenario>/ (default: build/).
  init  TARGET SCENARIO    Scaffold SCENARIO into TARGET/.claude/skills + TARGET/.github/skills.
  dev                      Assemble the `github` scenario into THIS repo's own
                           .claude/skills + .github/skills (the committed copies).

Python standard library only. No templating engine — generated SKILL.md files
read as plain prose; the only source-level construct is a `<!-- dobby:combined-seam:* -->`
anchor, which is substituted (combined) or stripped (all other scenarios) before output.
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
MANIFEST = SKILLS / "manifest.json"
HOSTS = (".claude/skills", ".github/skills")
SCENARIOS = ("ado", "github", "combined")

# Patterns that must NOT appear in generated output. Each becomes a build failure.
FORBIDDEN = [
    (re.compile(r"\{\{|\}\}|\{%|%\}"), "template/macro syntax"),
    (re.compile(r"dobby:combined-seam:"), "leftover combined-seam anchor"),
    (re.compile(r"dobby-(ado|gh)-[a-z-]+"), "reference to a retired backend skill (dobby-ado-* / dobby-gh-*)"),
    (re.compile(r"after backend resolution", re.I), "dispatcher 'backend resolution' prose"),
    (re.compile(r"resolves?\s+`?backend`?\b.*\bfrom\b.*config\.json", re.I), "runtime backend routing prose"),
    (re.compile(r"\.(?:github|claude)/skills/"), "host-specific skills path (reference skills by name instead)"),
    (re.compile(r"\bskills/(?:ado|github|combined|_common|_lib)/"), "source-repo tier path (use a bundled-relative path instead)"),
]


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def split_frontmatter(text):
    """Return (frontmatter_str_without_fences, body) or (None, text) if no frontmatter."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            fm = text[3:end].strip("\n")
            body = text[end + 4:]
            return fm, body.lstrip("\n")
    return None, text


def set_name(frontmatter, name):
    """Rewrite (or insert) the top-level `name:` field in a frontmatter block."""
    if frontmatter is None:
        return f"name: {name}"
    if re.search(r"(?m)^name:\s*.*$", frontmatter):
        return re.sub(r"(?m)^name:\s*.*$", f"name: {name}", frontmatter, count=1)
    return f"name: {name}\n{frontmatter}"


def rewrite_script_paths(body, scripts, owner_of):
    """Rewrite any reference to a known _lib script (whatever its source path prefix)
    to its bundled output location: <owner-skill>/scripts/<script>. Bundled once per
    scenario under the owner; non-owner skills reference the owner's path."""
    for script in scripts:
        owner = owner_of[script]
        out_ref = f"{owner}/scripts/{script}"
        # Match skills/_lib/<script>, skills/<anything>/scripts/<script>, or .github/.claude variants.
        pat = re.compile(r"(?:\.?[\w./-]*?/)?(?:_lib|scripts)/" + re.escape(script))
        body = pat.sub(out_ref, body)
    return body


def apply_seam(body, seam, fragment_text):
    """Replace the seam anchor line with the fragment (combined) or strip it (others)."""
    anchor = re.compile(r"^[ \t]*<!--[ \t]*dobby:combined-seam:[\w-]+[ \t]*-->[ \t]*\n?", re.M)
    if seam and fragment_text is not None:
        return anchor.sub(fragment_text.rstrip("\n") + "\n", body)
    return anchor.sub("", body)


def lint(name, text):
    # The generator's own provenance notice legitimately names the source tier;
    # exclude it so the tier-path rule checks only real skill prose.
    text = re.sub(r"<!-- Generated by scripts/build-skills\.py from [^>]*?-->", "", text, count=1)
    problems = []
    for pat, msg in FORBIDDEN:
        m = pat.search(text)
        if m:
            problems.append(f"  {name}: {msg} -> {m.group(0)!r}")
    return problems


def strip_copy_notice(body):
    return re.sub(r"^\s*<!--\s*This file is a copy of.*?-->\s*\n", "", body, count=1, flags=re.S)


def render_skill(out_name, source_dir, scripts, owner_of, seam=None, fragment_text=None, source_label=None):
    """Return the rendered SKILL.md text for one skill."""
    raw = (source_dir / "SKILL.md").read_text(encoding="utf-8")
    fm, body = split_frontmatter(raw)
    fm = set_name(fm, out_name)
    body = strip_copy_notice(body)
    body = apply_seam(body, seam, fragment_text)
    if scripts:
        body = rewrite_script_paths(body, scripts, owner_of)
    label = source_label or source_dir.relative_to(SKILLS).as_posix()
    notice = (f"<!-- Generated by scripts/build-skills.py from skills/{label}/SKILL.md — "
              f"do not edit this copy; edit the source and regenerate. -->\n")
    return f"---\n{fm}\n---\n\n{notice}\n{body.lstrip(chr(10))}"


def copy_aux(source_dir, dest_dir):
    """Copy a skill's templates/ (and any non-SKILL.md aux files) verbatim."""
    tmpl = source_dir / "templates"
    if tmpl.is_dir():
        shutil.copytree(tmpl, dest_dir / "templates", dirs_exist_ok=True)


def resolve_entry(manifest, scenario, skill, entry):
    """Resolve a manifest entry (handling combined `reuse`) to (source_dir, scripts, seam)."""
    if "reuse" in entry:
        base = manifest["scenarios"][entry["reuse"]][skill]
        source_dir = SKILLS / base["source"]
        scripts = list(base.get("scripts", []))
        seam = entry.get("seam")
        if seam:
            scripts += list(seam.get("scripts", []))
        return source_dir, scripts, seam, entry["reuse"]
    return SKILLS / entry["source"], list(entry.get("scripts", [])), entry.get("seam"), scenario


def owned_names(manifest):
    """Every skill name dobby's generator manages (across all scenarios). Anything
    NOT in this set — e.g. openspec-* installed by the OpenSpec CLI, or a project's
    own skills — is foreign and the generator must never touch it."""
    names = set(manifest["common"])
    for sc in manifest["scenarios"].values():
        names.update(sc.keys())
    return names


def assemble(manifest, scenario, dest_root):
    """Assemble one scenario into dest_root (a flat dir of skill folders).

    Non-destructive: only dobby-owned skill folders are written, and only
    dobby-owned folders that don't belong to this scenario are pruned. Foreign
    skill folders (openspec-*, a project's own skills) are left untouched.
    Returns lint problems (a non-empty list means nothing was written)."""
    owner_of = {s: meta["owner"] for s, meta in manifest["lib"].items()}
    problems = []
    rendered = {}   # name -> SKILL.md text
    sources = {}    # name -> source dir (for templates / aux files)
    used_scripts = {}  # script -> owner (collected for bundling)

    # 1. scenario-independent skills (verbatim, name = folder)
    for name in manifest["common"]:
        src = SKILLS / "_common" / name
        rendered[name] = render_skill(name, src, [], owner_of, source_label=f"_common/{name}")
        sources[name] = src

    # 2. scenario-specialized work-item skills
    for skill, entry in manifest["scenarios"][scenario].items():
        source_dir, scripts, seam, src_scenario = resolve_entry(manifest, scenario, skill, entry)
        fragment_text = None
        if seam:
            fragment_text = (SKILLS / seam["fragment"]).read_text(encoding="utf-8")
        rendered[skill] = render_skill(
            skill, source_dir, scripts, owner_of,
            seam=seam, fragment_text=fragment_text,
            source_label=source_dir.relative_to(SKILLS).as_posix(),
        )
        sources[skill] = source_dir
        for s in scripts:
            used_scripts[s] = owner_of[s]

    # 3. lint every rendered skill (after seam substitution + path rewrite)
    for name, text in rendered.items():
        problems += lint(name, text)
    if problems:
        return problems

    dest_root.mkdir(parents=True, exist_ok=True)
    current = set(rendered)

    # 4. prune ONLY dobby-owned skills that don't belong to this scenario;
    #    never remove foreign folders (openspec-*, project skills).
    for name in owned_names(manifest) - current:
        stale = dest_root / name
        if stale.exists():
            shutil.rmtree(stale)

    # 5. write each owned skill into a clean per-skill folder (leaves siblings intact)
    for name, text in rendered.items():
        d = dest_root / name
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True, exist_ok=True)
        (d / "SKILL.md").write_text(text, encoding="utf-8", newline="\n")
        copy_aux(sources[name], d)

    # 6. bundle each used _lib script once, under its owner skill's scripts/
    for script, owner in used_scripts.items():
        owner_scripts = dest_root / owner / "scripts"
        owner_scripts.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SKILLS / "_lib" / script, owner_scripts / script)

    return []


def clean_skill_tree(path):
    """Fully reset a directory. Used only for the throwaway `build/` artifact —
    never for a real project's host dirs (see assemble's non-destructive writes)."""
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def cmd_build(args):
    manifest = load_manifest()
    out = Path(args.out)
    for scenario in SCENARIOS:
        dest = out / scenario
        clean_skill_tree(dest)
        problems = assemble(manifest, scenario, dest)
        if problems:
            print(f"[FAIL] lint failed for scenario '{scenario}':", file=sys.stderr)
            print("\n".join(problems), file=sys.stderr)
            return 1
        print(f"[ok] built {scenario} -> {dest.relative_to(REPO) if dest.is_relative_to(REPO) else dest}")
    return 0


def write_scenario_to_hosts(manifest, scenario, target_root):
    # Non-destructive: assemble() only manages dobby-owned skill folders under each
    # host dir, so anything already there (openspec-*, a project's own skills) survives.
    for host in HOSTS:
        dest = Path(target_root) / host
        problems = assemble(manifest, scenario, dest)
        if problems:
            print(f"[FAIL] lint failed assembling '{scenario}' into {dest}:", file=sys.stderr)
            print("\n".join(problems), file=sys.stderr)
            return 1
        print(f"[ok] wrote {scenario} -> {dest}")
    return 0


def print_openspec_hint(target):
    print()
    print("dobby does not bundle the OpenSpec workflow skills -- install them with the")
    print("OpenSpec CLI so they stay current and self-managed:")
    print(f"  cd {target}")
    print('  openspec init --tools "claude,github-copilot"')
    print("(dobby's non-destructive init leaves those skills untouched on re-runs.)")


def cmd_init(args):
    if args.scenario not in SCENARIOS:
        print(f"[FAIL] unknown scenario '{args.scenario}'. Choose one of: {', '.join(SCENARIOS)}", file=sys.stderr)
        return 2
    target = Path(args.target)
    if not target.is_dir():
        print(f"[FAIL] target project directory does not exist: {target}", file=sys.stderr)
        return 2
    code = write_scenario_to_hosts(load_manifest(), args.scenario, target)
    if code == 0:
        print_openspec_hint(target)
    return code


def cmd_dev(args):
    # dobby develops against the github flow (issues + PRs).
    return write_scenario_to_hosts(load_manifest(), "github", REPO)


def main(argv=None):
    p = argparse.ArgumentParser(prog="build-skills.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="mode", required=True)

    b = sub.add_parser("build", help="emit all three scenarios to a build dir")
    b.add_argument("--out", default=str(REPO / "build"))
    b.set_defaults(func=cmd_build)

    i = sub.add_parser("init", help="scaffold a scenario into a target project")
    i.add_argument("target", help="path to the target project root")
    i.add_argument("scenario", help=f"one of: {', '.join(SCENARIOS)}")
    i.set_defaults(func=cmd_init)

    d = sub.add_parser("dev", help="self-install the github scenario into this repo")
    d.set_defaults(func=cmd_dev)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
